name: Deploy GitSite to Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install gitsite-cli -g

    - name: Ensure template files are available
      run: |
        # Ensure the book.html template file is present
        if [ ! -f "path/to/book.html" ]; then
          echo "book.html template file is missing. Please add it to the repository."
          exit 1
        fi

    - name: Build site
      run: gitsite-cli build -o _site -v

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        branch: gh-pages
        folder: _site
		